### ISSUE TITLE
div2007 - Fatal Error

### ISSUE THREAD

**Issue by Gorli** [franzholz/div2007#1]
Hello!

My environment: TYPO3 7.6.9, DIV2007, Agency 0.3.1

When editing a user profile in the FE, I get after sending the following error message.

`1: PHP Catchable Fatal Error: Argument 1 passed to tx_div2007_email::embedMedia() must be an instance of t3lib_mail_Message, instance of TYPO3\CMS\Core\Mail\MailMessage given, called in ..../typo3conf/ext/div2007/class.tx_div2007_email.php on line 215 and defined in .../typo3conf/ext/div2007/class.tx_div2007_email.php line 395`

**Comment by Gorli** [comment]
... Same error message when you create an account

**Comment by franzholz** [comment]
Hello Gorli,
thanks for the bug message.
Change the file class.tx_div2007_email.php.
    static public function embedMedia ($mail, $htmlContent) {
line 395
Then it will work.
Regards,
Franz

```
Le Lundi 18 juillet 2016 14h13, Gorli <notifications@github.com> a écrit :
```

 ... Same error message when you create an account—

**Comment by Gorli** [comment]
Hello Franz,
I have enjoyed doing and happy also about the answer!
Best regards
Gorli
