### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by markustobler** [franzholz/div2007#10]
Hi

We had a error when we use PHP 7.2 in the file «class.tx_div2007_alpha5.php». In the attached file you can find our fix in line 559/560.

Thanks for updating your extension.
Markus
[class.tx_div2007_alpha5.php.zip](https://github.com/franzholz/div2007/files/2179536/class.tx_div2007_alpha5.php.zip)

**Comment by franzholz** [comment]
see my patch
