### ISSUE TITLE
Tab API sources always added in tt_products detail view

### ISSUE THREAD

**Issue by sebkln** [franzholz/div2007#11]
I'm using `div2007` (v1.10.10) and `tt_products` (v3.0.0).

In the **product detail view**, `div2007` always adds the following sources:

    <script type="text/javascript" src="/typo3conf/ext/div2007/Resources/Public/JavaScript/jsfunc.tab.js?1540562104"></script>     
    <link rel="stylesheet" href="/typo3conf/ext/div2007/Resources/Public/Css/tab.css?1540562104" type="text/css" />

How can I prevent that? Is this a bug or a misconfiguration? I don't use any `###TAB_HEADER_` or `###TAB_BOX_` markers in my templates.

**Comment by franzholz** [comment]
Check your tt_products setup.

    plugin.tt_products.js.ALL.tab.file = ...
    plugin.tt_products.js.ALL.tab.css = ...
