### ISSUE TITLE
invalid issue

### ISSUE THREAD

**Issue by Gorli** [franzholz/div2007#2]
Hello!
With the current master version I get in BE (open User folder) following 
![error](https://cloud.githubusercontent.com/assets/4998028/17440575/72fe0a82-5b2d-11e6-9506-caaab28846c1.PNG)
error
#1195567840: $hookObject must implement interface TYPO3\CMS\Recordlist\RecordList\RecordListHookInterface

**Comment by franzholz** [comment]
This is about gridelements and not div2007.

**Comment by Gorli** [comment]
sorry that I have inadvertently addressed incorrectly
