### ISSUE TITLE
Error at the BE after upgrading from 1.6 to 1.7 version

### ISSUE THREAD

**Issue by wabajwa** [franzholz/div2007#4]
Hi, 
I am using Typo3 7.6.16 and Php 7. recently i just did the `composer update`with out changing any thing in my composer.json file and it upgraded the div2007 from 1.6 to 1.7 but when i went to my admin tools>Extensions, i lost the view and getting the following error. 
![image](https://cloud.githubusercontent.com/assets/24478656/24600232/f17ac240-1853-11e7-9804-944333086faa.png)
with further lines under it like, 

TYPO3\CMS\Core\Package\Exception\InvalidPackageManifestException thrown in file
/home/www/wwwdev/vendor/typo3/cms/typo3/sysext/core/Classes/Package/PackageManager.php in line 948.

Now, i don't have any idea, what could be the error, as i didn't change any thing, its just a simple upgrade. 
I am looking for your kind response.
Thanks

regards
Bajwa

**Comment by franzholz** [comment]
div2007 1.7.0 uses a file composer.json. You must update it to the latest file from this Github page.

**Comment by wabajwa** [comment]
Thank you so much, it worked for me.
