### ISSUE TITLE
PHP Fatal error:  Only variables can be passed by reference in .../typo3conf/ext/div2007/class.tx_div2007_alpha5.php on line 2744

### ISSUE THREAD

**Issue by mesurinna** [franzholz/div2007#5]
I am getting this PHP error on PHP7 while using your actual Extension on a tt_products Plugin. I wrote yet in an github project about this, but error is still there.

In class.tx_div2007_alpha5.php there is this snippet:

foreach ($GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_page.php']['addEnableColumns'] as $_funcRef) {
							$query .= t3lib_div::callUserFunction($_funcRef, $_params, 'tx_div2007_alpha5');
}

The error is produced cos of this static function call where a fixed value 'tx_div2007_alpha5' is given as a param, which is invalid and crashes. U just need to put this into a variable and pass the variable and all is fine.

**Comment by franzholz** [comment]
I have fixed this issue now:

https://github.com/franzholz/div2007/commit/a958af87bad5b59d44ac6e93dfa116a032fb43ca

**Comment by franzholz** [comment]
A second bugfix for a duplicated code has been necessary:

https://github.com/franzholz/div2007/commit/b3abb1188c6df546f062bf21245f98cb1e9857e2
