### ISSUE TITLE
Use secure mode and padding scheme.

### ISSUE THREAD

**Issue by CrosClemence** [franzholz/div2007#67]
Hello,

I use SonarQube to enhance my code and detect potential security flaws in my projects, and it flagged to me that this file "Classes/Security/StorageSecurity.php" has this security vulnerability "Use secure mode and padding scheme." due to this function "openssl_public_encrypt".

Could you please look into this issue to see if a fix could be proposed ?

**Comment by franzholz** [comment]
https://security.stackexchange.com/questions/52665/which-is-the-best-cipher-mode-and-padding-mode-for-aes-encryption

I do not think that this will be changed in the future.
This password encryption is used only for autologin.
Every user should be told to immediately change his password after a successful first login.

**Comment by franzholz** [comment]
Done:

https://github.com/franzholz/div2007/pull/68
