### ISSUE TITLE
composer autoload class alias map cannot handle TYPO3_version

### ISSUE THREAD

**Issue by CDRO** [franzholz/div2007#7]
https://github.com/franzholz/div2007/blob/a0f9cdcaa6dacc4d949793cf3b16f0e20153d9e3/Migrations/Code/ClassAliasMapResult.php#L940

It seems that composer autoload is not a big fan of the TYPO3_version constant and throws an error when trying to install div2007.

I'll make an MR with a fix for this.

Regards
Tizian

**Comment by CDRO** [comment]
<img width="1680" alt="bildschirmfoto 2018-04-30 um 15 30 56" src="https://user-images.githubusercontent.com/6471286/39429573-8d269ea0-4c8b-11e8-97ca-dce487862415.png">

**Comment by franzholz** [comment]
The class alias map has now been completely removed from extension div2007, since version 1.10.0

https://github.com/franzholz/div2007/commit/f37a3a528c306d824843bae139438ab7e0368c09

Install the extension migration_core instead to get the correct migration class alias map.

**Comment by CDRO** [comment]
This solves everything I think, thanks a lot!
